# Generated by Django 4.1.5 on 2023-01-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('infected', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('reports', models.IntegerField(default=0)),
                ('water', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('medication', models.IntegerField(default=0)),
                ('ammunition', models.IntegerField(default=0)),
            ],
        ),
    ]
